# Generated by Django 2.0 on 2018-09-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180727_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
