# Generated by Django 2.0 on 2018-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180911_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='avatar',
            field=models.ImageField(default='pictures/logo-white.png', upload_to='pictures/'),
        ),
    ]
